name: Docker Image CI

on:
  push:
    branches: [ "Python-3.9.17" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'linux/amd64'
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    -  name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pyutils:${{ github.sha }},${{ secrets.DOCKER_HUB_USERNAME }}/pyutils:python-3.9.17
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
          
